const {
  Products,
  ProductsCommon,
  PackagingSupplies,
  PackagingSuppliesCommon,
  Assembly,
  AssemblyCommon,
  Kit,
  KitCommon,
  MRO,
  MROCommon,
  RawMaterial,
  RawMaterialCommon,
  NonInventory,
  NonInventoryCommon,
  Phantom,
  PhantomCommon
} = require("./ItemTypeSchemas");

module.exports = {
  ConfigurationModel: require("./configuration"),
  CounterModel: require("./Counter"),
  SupplierModel: require("./Supplier"),
  ProductListsModel: require("./ProductLists"),
  ABCClassificatonModel: require("./ABCClassification"),
  ItemModel: require("./Item"),
  ItemSharedAttributesModel: require("./ItemSharedAttributes"),
  Products,
  ProductsCommon,
  PackagingSupplies,
  PackagingSuppliesCommon,
  Assembly,
  AssemblyCommon,
  Kit,
  KitCommon,
  MRO,
  MROCommon,
  RawMaterial,
  RawMaterialCommon,
  NonInventory,
  NonInventoryCommon,
  Phantom,
  PhantomCommon
};
