const { UserModel } = require('../models/index'); // Path to your User model
let rootUserData = {
    // id is email-usertype
    _id: 'root-user@default.com-admin',
    givenName: "root-user",
    lastName: "wms",
    email: "root-user@default.com",
    password: "$2a$10$kY7hCXWy2Je7SHsgGLNsY.8BdaHoBuawpdZws.Sb3o7QN4s58EyRO",
    autoGeneratePassword: false,
    type: "admin",
    salt: "$2a$10$kY7hCXWy2Je7SHsgGLNsY.",
    role: "admin",
    status: "default",
    createdAt: 1714648726971,
    updatedAt: 1714648726971,
    lastLoginAt: null,
    activity: [
      {
        key: "",
        email: "",
        role: "",
        date: 1714648726971,
        activity: "User created by default",
        changes: [],
      },
    ],
};


async function seedDatabase() {
    try {
        // Check for existing root user
        const rootUserExists = await UserModel.findOne({ email: 'root-user@default.com' });
        if (!rootUserExists) {
            const rootUser = new UserModel(rootUserData);
            await rootUser.save();
            console.log('Root user created');
        } else {
            console.log('Root user already exists');
        }

        // Add other default entities similarly
    } catch (error) {
        console.error('Error seeding database:', error);
    }
}

// {
//     "status": 1,
//     "type": "success",
//     "responseMessage": "List of Attributes",
//     "data": {
//         "variantId": {
//             "required": true,
//             "included": true,
//             "autoGenerated": true,
//             "prefix": ""
//         },
//         "_id": "673c29531f6cd3fc24ce9099",
//         "productName": {
//             "required": true,
//             "included": true
//         },
//         "productDescription": {
//             "required": true,
//             "included": true
//         },
//         "productCategory": {
//             "required": true,
//             "included": true
//         },
//         "unit_of_measure": {
//             "required": false,
//             "included": true
//         },
//         "serial_lot_tracking": {
//             "required": true,
//             "included": true
//         },
//         "productImages": {
//             "required": false,
//             "included": true
//         },
//         "productDocs": {
//             "required": true,
//             "included": true
//         },
//         "supplierId": {
//             "required": true,
//             "included": true
//         },
//         "supplierName": {
//             "required": true,
//             "included": true
//         },
//         "supplierPartDescription": {
//             "required": true,
//             "included": true
//         },
//         "alternate_supplier": {
//             "required": false,
//             "included": true
//         },
//         "alternateSupplierId": {
//             "required": true,
//             "included": true
//         },
//         "alternateSupplierName": {
//             "required": true,
//             "included": true
//         },
//         "alternateSupplierPartDescription": {
//             "required": true,
//             "included": true
//         },
//         "preferredSupplier": {
//             "required": true,
//             "included": true
//         },
//         "packagingType": {
//             "required": true,
//             "included": true
//         },
//         "storageRequirements": {
//             "required": true,
//             "included": true
//         },
//         "shelfSpaceRequirements": {
//             "required": true,
//             "included": true
//         },
//         "handlingInstructions": {
//             "required": true,
//             "included": true
//         },
//         "inspectionRequirements": {
//             "required": true,
//             "included": true
//         },
//         "materialComposition": {
//             "required": true,
//             "included": true
//         },
//         "customizationOptions": {
//             "required": true,
//             "included": true
//         },
//         "associatedServices": {
//             "required": true,
//             "included": true
//         },
//         "safetyInfo": {
//             "required": true,
//             "included": true
//         },
//         "countryOfOrigin": {
//             "required": true,
//             "included": true
//         },
//         "regulatoryCompliance": {
//             "required": true,
//             "included": true
//         },
//         "energyConsumption": {
//             "required": true,
//             "included": true
//         },
//         "carbonFootPrint": {
//             "required": true,
//             "included": true
//         },
//         "endOfLifeDisposal": {
//             "required": true,
//             "included": true
//         },
//         "warrantyInformation": {
//             "required": true,
//             "included": true
//         },
//         "replacementPartsInfo": {
//             "required": true,
//             "included": true
//         },
//         "returnsPolicies": {
//             "required": true,
//             "included": true
//         },
//         "sellingConditions": {
//             "required": true,
//             "included": true
//         },
//         "variantSupplierPartNumber": {
//             "required": true,
//             "included": true
//         },
//         "variantAlternateSupplierPartNumber": {
//             "required": true,
//             "included": true
//         },
//         "productSKU": {
//             "required": true,
//             "included": true
//         },
//         "productColor": {
//             "required": true,
//             "included": true
//         },
//         "productSize": {
//             "required": true,
//             "included": true
//         },
//         "weight_and_dimensions": {
//             "required": true,
//             "included": true
//         },
//         "weightUnit": "kg",
//         "lengthUnit": "cm",
//         "storageLocations": {
//             "required": false,
//             "included": true
//         },
//         "product_pricing": {
//             "required": true,
//             "included": true
//         },
//         "stocks_and_reorder": {
//             "required": true,
//             "included": true
//         },
//         "counting_method_section": {
//             "required": true,
//             "included": true
//         },
//         "activity": {
//             "key": "usama.ayub@3dlogistix.com-employee",
//             "email": "usama.ayub@3dlogistix.com",
//             "role": "employee",
//             "date": 1732070989510,
//             "description": "Product Configuration Updated",
//             "status": "",
//             "changes": []
//         },
//         "createdAt": 1731995987119,
//         "updatedAt": 1732070989512
//     }
// }


module.exports = {seedDatabase};
